[[overview]]

This section provides you with a detailed overview of the out-of-the-box Spring Cloud Stream Applications.
It assumes familiarity with general Spring Cloud Stream concepts, which you can find in the Spring Cloud Stream https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/{scst-core-version}/[reference documentation].

These Spring Cloud Stream Applications provide you with out-of-the-box Spring Cloud Stream utility applications that you can run independently or with Spring Cloud Data Flow. They include:

* Connectors (sources, processors, and sinks) for a variety of middleware technologies, including message brokers, storage (relational, non-relational, filesystem).
* Adapters for various network protocols.
* Generic processors that you can customize with https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/expressions.html[Spring Expression Language (SpEL)] or by scripting.

You can find a detailed listing of all the applications and their options in the <<starters,corresponding>> section of this guide.

== Pre-built Applications

Out-of-the-box applications are Spring Boot applications that include a Binder implementation on top of the basic logic of the app (a function for example) -- a fully functional uber-jar.
These https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/getting-started.html#getting-started-first-application-executable-jar[uber-jars] include the minimal code required for standalone execution.
For each function application, the project provides a prebuilt version for Apache Kafka and Rabbit MQ Binders.

[NOTE]
Prebuilt applications are generated according to the https://github.com/spring-cloud/spring-cloud-app-starters-maven-plugins/tree/master/spring-cloud-stream-app-maven-plugin[stream apps generator Maven plugin].

[[classification]]
== Classification

Based on their target application type, they can be either:

* A _source_ that connects to an external resource to poll and receive data that is published to the default "`output`" channel;
* A _processor_ that receives data from an "`input`" channel and processes it, sending the result on the default "`output`" channel;
* A _sink_ that connects to an external resource to send the received data to the default "`input`" channel.

The prebuilt applications follow a naming convention: `<functionality>-<type>-<binder>`. For example, `rabbit-sink-kafka` is a _Rabbit sink_ that uses the Kafka binder that is running with Kafka as the middleware.

=== Maven and Docker Access

The core functionality of the applications is available as functions.
See the https://github.com/pivotal/java-functions[Java Functions] repository for more details.
Prebuilt applications are available as Maven artifacts.
You can download the executable jar artifacts from the Spring Maven repositories.
The root directory of the Maven repository that hosts release versions is https://repo.spring.io/release/org/springframework/cloud/stream/app/.
From there, you can navigate to the latest released version of a specific app -- for example, link:https://repo.spring.io/release/org/springframework/cloud/stream/app/log-sink-rabbit/2.0.2.RELEASE/log-sink-rabbit-1.1.1.RELEASE.jar[log-sink-rabbit-2.0.2.RELEASE.jar].
You need to use the link:https://repo.spring.io/milestone/org/springframework/cloud/stream/app[Milestone] and link:https://repo.spring.io/snapshot/org/springframework/cloud/stream/app[Snapshot] repository locations for Milestone and Snapshot executable jar artifacts.

The Docker versions of the applications are available in Docker Hub, at `https://hub.docker.com/r/springcloudstream/`.
Naming and versioning follows the same general conventions as Maven -- for example:

====
[source,bash]
----
docker pull springcloudstream/cassandra-sink-kafka
----
====

The preceding command pulls the latest Docker image of the _Cassandra sink_ with the Kafka binder.

=== Building the Artifacts

You can build the project and generate the artifacts (including the prebuilt applications) on your own.
This is useful if you want to deploy the artifacts locally or add additional features.
If you are at the root of the repository, https://github.com/spring-cloud-stream-app-starters/stream-applications[steam-applications], doing a maven build generates the entire binder based apps.
If you do not want to do that and instead only are interested in a certain application, then `cd` into the right module and invoke the build from there.
Then run the following Maven command:

====
[source,bash]
----
mvn clean package
----
====

This command generates the applications. By default, the generated projects are placed under a directory called `apps`.
There, you can find the binder based applications, which you can then build and run.

== Patching Pre-built Applications

If you are looking to patch the pre-built applications to accommodate the addition of new dependencies, you can use the following example as the reference.
To add `mysql` driver to `jdbc-sink` application:

. Clone the GitHub repository at https://github.com/spring-cloud-stream-app-starters/stream-applications

. Open it in an IDE and make the necessary changes in the right generator project. The repository is organized as `source-apps-generator`, `sink-apps-generator`, and `processor-apps-generator`.
+
Find the module that you want to patch and make the changes. For example, you can add the following to the generator plugin's configuration in the pom.xml:
+
====
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.37</version>
  </dependency>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
  </dependency>
</dependencies>
----
====

. Generate the binder based apps as specified above and build the apps.
