== Stream applications

This repository provides a collection of components that help with various data integration use cases.
It provides standalone Java functions that can be reused in end-user applications.

In addition to providing these functions, this repository is also used to generate out of the box Spring Cloud Stream applications those using the functions as a baseline.
These applications can be run standalone as Spring Cloud Stream applications or as part of a data flow such as the one orchestrated using Spring Cloud Data Flow.

The repository is divided into two sections - `Functions` and `Applications`. The former is used for hosting the various functions and the latter is for generating the apps.

The following are the four major components of this repository.

* https://github.com/spring-cloud/stream-applications/tree/master/functions[Standalone Java Functions] as java.util.function.Function/Consumer/Supplier
* https://github.com/spring-cloud/stream-applications/tree/master/applications/stream-applications-core[Core components] for the out of the applications
* https://github.com/spring-cloud/stream-applications/tree/master/applications[Out of the box Spring Cloud Stream applications] as Source/Sink/Processor
* https://github.com/spring-cloud/stream-applications/tree/master/applications/stream-applications-build[Aggregator] for the out of the box applications.

=== Available Functions


|===
|Supplier |Consumer |Function

|File
|Cassandra
|Filter
|HTTP
|Counter
|Header-Enricher
|JDBC
|File
|SpEL
|MongoDB
|FTP
|Splitter
|MQTT
|JDBC
|
|TCP
|Log
|
|Time
|MongoDB
|
|
|MQTT
|
|
|Rabbit
|
|
|Redis
|
|
|SFTP
|
|
|TCP
|
|===

=== Available Spring Cloud Stream Applications

|===
|Source |Sink |Processor

|File
|Cassandra
|Bridge
|HTTP
|Counter
|Filter
|JDBC
|File
|Groovy
|Load-Generator
|FTP
|Header-Enricher
|MongoDB
|JDBC
|Script
|MQTT
|Log
|Splitter
|TCP
|MongoDB
|Transform
|Time
|MQTT
|
|
|Rabbit
|
|
|Redis
|
|
|Router
|
|
|SFTP
|
|
|TCP
|
|
|Throughput
|
|===


=== Build

You can build everything from the root of the repository.

`./mvnw clean install`

But, this may not be what you are interested in doing since you are probably interested in a single application or a few of them.
In order to build the functions and applications that you are interested in, you need to build them selectively as shown below.

==== Building functions

`./mvnw clean install -f functions`

You can also build a single function or group of functions.
For e.g if you are only interested in jdbc-supplier and log-consumer, do the following.

`./mvnw clean install -pl :jdbc-suppler,:log-consumer`

==== Building core for Stream Applications

`./mvnw clean install -f applicaitons/stream-applications-core`

=== Building the applications

Let's assume that you want to build JDBC Source application based on Kafka Binder in Spring Cloud Stream and Log Sink application based on Rabbit binder.
Here is what you need to do.
Assuming that you built both functions and stream-applications-core as above.

```
./mvnw clean package -pl :jdbc-source
cd applications/source/jdbc-source/apps/jdbc-source-kafka
./mvnw clean package
```

This will generate the Kafka binder based uber jar in the target folder.

Similarly for the log sink, do the following.

```
./mvnw clean package -pl :log-sink
cd applications/sink/log-sink/apps/log-sink-rabbit
./mvnw clean package
```

=== Code of Conduct

Please see our https://github.com/spring-projects/.github/blob/master/CODE_OF_CONDUCT.md[Code of Conduct]