name: 'Install xsltproc'
description: 'Install xsltproc'

runs:
  using: composite
  steps:
    - name: 'Install xsltproc'
      shell: bash
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -q -y xsltproc
