name: 'Install Packeto Buildpacks'
description: 'Install Packeto Buildpacks'

runs:
  using: composite
  steps:
    - name: 'Install Pack'
      shell: bash
      run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.27.0/pack-v0.27.0-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
