= AWS S3 Consumer

A consumer that allows you to upload files to AWS S3.
The consumer uses the AWS S3 support from Spring Integration and Spring Cloud AWS.

== Beans for injection

You can import `AwsS3ConsumerConfiguration` in the application and then inject the following bean.

`Consumer<Message<?>> s3Consumer`

You can use `s3Consumer` as a qualifier when injecting.

== Configuration Options

All configuration properties are prefixed with `s3.consumer`.
There are also properties that need to be used with the prefix `s3.common`.

For more information on the various options available, please see link:src/main/java/org/springframework/cloud/fn/consumer/s3/AwsS3ConsumerProperties.java[AwsS3ConsumerProperties] and `io.awspring.cloud.autoconfigure.s3.properties.S3Properties` & `io.awspring.cloud.autoconfigure.s3.properties.S3CrtClientProperties` from Spring Cloud AWS auto-configuration.

== Examples

See this link:src/test/java/org/springframework/cloud/fn/consumer/s3[test suite] for the various ways, this consumer is used.

== Other usage

See this https://github.com/spring-cloud/stream-applications/blob/master/applications/sink/s3-sink/README.adoc[README] where this consumer is used to create a Spring Cloud Stream based S3 Sink application.
