name: 'scale-down'
description: 'Scale Down Private GitHub Runners'

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: boolean
        default: false
      max_parallel:
        type: number
        required: true
    secrets:
      GCP_CRED_JSON:
        required: false
      TMC_API_TOKEN:
        required: false
jobs:
  scale-down:
    runs-on: ubuntu-latest
    concurrency:
      group: stream-apps-gh-runners
      cancel-in-progress: false
    steps:
      - name: 'Configure: Checkout'
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: 'Action: Ensure scripts are executable'
        shell: bash
        run: find . -type f -name "*.sh" -exec chmod a+x '{}' \;
      - name: 'Configure: Runners Cluster provider'
        shell: bash
        run: |
          RUNNER_TYPE=$(./scripts/determine-provider.sh stream-apps-gh-runners)
          if [ "$RUNNER_TYPE" != "gke" ]; then
            RUNNER_TYPE=tmc
          fi
          echo "RUNNER_TYPE=$RUNNER_TYPE" >> $GITHUB_ENV
      - name: 'Install: gcloud cli'
        if: ${{ env.RUNNER_TYPE == 'gke' }}
        uses: ./.github/actions/install-gcloud
      - name: 'Action: gcloud auth'
        if: ${{ env.RUNNER_TYPE == 'gke' }}
        id: auth_gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GCP_CRED_JSON }}
      - name: 'Configure: Install TMC'
        if: ${{ env.RUNNER_TYPE == 'tmc' }}
        uses: ./.github/actions/install-tmc
      - name: 'Action: Login to TMC'
        if: ${{ env.RUNNER_TYPE == 'tmc' }}
        uses: ./.github/actions/auth-tmc
        with:
          tmc_api_token: '${{ secrets.TMC_API_TOKEN }}'
      - name: 'Action: Decrease runners with ${{ inputs.max_parallel }}'
        timeout-minutes: 10
        uses: ./.github/actions/decrease-runners
        with:
          dec: ${{ inputs.max_parallel }}
